#!/bin/sh

if [ -e ../zapish.inc ]; then
	. ../zapish.inc
elif [ -e /usr/libexec/zapish/zapish.inc ]; then
	. /usr/libexec/zapish/zapish.inc
else
	echo "No zapish.inc found"
	exit 1
fi

template_name="ICMP"

zapish_result=$(zabbix_api template.get \
		$(json_list params \
		$(json_str output simple \
			$(json_list filter \
				$(json_array_str "name" \
					"${template_name}" \
				"") \
			"")) \
		"")
	)

zapish_result=$(zabbix_api configuration.export \
	$(json_list params \
		$(json_list options \
			$(json_array_num templates \
				$(json_get "${zapish_result}" '.result[].templateid') \
			"") \
		"") \
		$(json_str format xml \
		"") \
	"")
)
echo ${zapish_result} > ${template_name}.raw
