#!/bin/sh
#
# zapish - Zabbix API SHell command processor
# This program is free software, distributed under the terms of
# the GNU General Public License Version 2.
#
# Copyright (C) 2017-2018 Tomasz Kłoczko <kloczek@fedoraproject.org>
#

if [ -e ./zapish.inc ]; then
	. ./zapish.inc
elif [ -e /usr/libexec/zapish/zapish.inc ]; then
	. /usr/libexec/zapish/zapish.inc
else
	echo "No zapish.inc found"
	exit 1
fi
#---------------------------------------------
# Main commands

# delete
zapish_add() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish add "
			# TODO: [actions|screens|slideshows|groups|items|hosts|templates|users]
			echo
			;;
		esac
		shift
	done
}

# delete
zapish_delete() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish delete "
			# TODO: [actions|screens|slideshows|groups|items|hosts|templates|users]
			echo
			;;
		esac
		shift
	done
}

# dump
zapish_export() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish export template '<template_name>' [-o <file_name>]"
			# TODO: ?
			echo
			;;
		esac
		shift
	done
}

# get
zapish_get() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish get "
			# TODO: [host <interface|description>|template <description|macros>]
			echo
			;;
		esac
		shift
	done
}

# help
zapish_help() {
	echo "Usage:"
	zapish_add	help
	zapish_delete	help
	zapish_export	help
	zapish_get	help
	echo "  zapish help"
	echo
	zapish_import	help
	zapish_list	help
	zapish_set	help
	zapish_show	help
}
# import
zapish_import() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish import "
			# TODO: [template|regexp] <file>"
			echo
			;;
		esac
		shift
	done
}

# list
zapish_list() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish list "
			# TODO: [actions|screens|slideshows|groups|items|hosts|templates|users]
			echo
			;;
		esac
		shift
	done
}

# set
zapish_set() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish set"
			# TODO: [action|host <interface|macro|viseable-name>]
			echo
			;;
		esac
		shift
	done
}

# show
zapish_show() {
	while [ $# -gt 0 ]; do
		case "${1}" in
		"help" )
			echo "  zapish show "
			# TODO: [actions|screens|slideshows|groups|items|hosts|templates|users]
			echo
			;;
		esac
		shift
	done
}

#---------------------------------------------
# main()

if [ $# = 0 ]; then
	zapish_help
	exit 1
fi

while [ $# -gt 0 ]; do
	case "${1}" in
	"add" )
		;;
	"delete" )
		;;
	"dump" )
		;;
	"get" )
		;;
	"help" )
		zapish_help
		;;
	"set" )
		;;
	"show" )
		;;
	esac
	shift
done
