#!/bin/sh
#
# zapish - Zabbix API SHell command processor
# This program is free software, distributed under the terms of
# the GNU General Public License Version 2.
#
# Copyright (C) 2017-2018 Tomasz Kłoczko <kloczek@fedoraproject.org>
#

if [ -e ./zapish.inc ]; then
	. ./zapish.inc
elif [ -e /usr/libexec/zapish/zapish.inc ]; then
	. /usr/libexec/zapish/zapish.inc
else
	echo "Not found /usr/libexec/zapish/zapish.inc"
	exit 1
fi

#---------------------------------------------
# Main commands

# delete
zapish_acknowledge() {
	while [ $# -gt 0 ]; do
		cmd="${1}"
		shift
		case "${cmd}" in
		"help" )
			echo "  zapish acknowledge "
			# TODO: [event]
			echo
			;;
		esac
	done
}

# delete
zapish_create() {
	while [ $# -gt 0 ]; do
		cmd="${1}"
		shift
		case "${cmd}" in
		"help" )
			echo "  zapish create "
			# TODO: [action|screen|slideshow|group|item|host|template|user]
			echo
			;;
		esac
	done
}

# delete
zapish_delete() {
	while [ $# -gt 0 ]; do
		cmd="${1}"
		shift
		case "${cmd}" in
		"help" )
			echo "  zapish delete "
			# TODO: [action|screen|slideshow|group|item|host|template|user]
			echo
			;;
		esac
	done
}

# dump
zapish_export() {
	while [ $# -gt 0 ]; do
		cmd="${1}"
		shift
		case "${cmd}" in
		"help" )
			echo "  zapish export template '<template_name>' [-o <file_name>]"
			# TODO: [template]
			echo
			;;
		esac
	done
}

# get
zapish_get() {
	while [ $# -gt 0 ]; do
		cmd="${1}"
		shift
		case "${cmd}" in
		"help" )
			echo "  zapish get "
			# TODO: [host <interface|description>|template <description|macros>]
			echo
			;;
		esac
	done
}

# help
zapish_help() {
	echo "Usage:"
	zapish_acknowledge	help
	zapish_create		help
	zapish_delete		help
	zapish_export		help
	zapish_get		help
	echo "  zapish help"
	echo
	zapish_import		help
	zapish_update		help
}

# import
zapish_import() {
	while [ $# -gt 0 ]; do
		cmd="${1}"
		shift
		case "${cmd}" in
		"help" )
			echo "  zapish import "
			# TODO: [template|regexp] <file>"
			echo
			;;
		esac
	done
}

# update
zapish_update() {
	while [ $# -gt 0 ]; do
		cmd="${1}"
		shift
		case "${cmd}" in
		"help" )
			echo "  zapish update"
			# TODO: [action|host <interface|macro|viseable-name>]
			echo
			;;
		esac
	done
}

#---------------------------------------------
# main()

if [ $# = 0 ]; then
	zapish_help
	exit 1
fi

while [ $# -gt 0 ]; do
	cmd="${1}"
	shift
	case "${cmd}" in
	"acknowledge" )
		;;
	"create" )
		;;
	"delete" )
		;;
	"dump" )
		;;
	"get" )
		;;
	"help" )
		zapish_help
		;;
	"update" )
		;;
	* )
		zapish_help
		;;
	esac
	shift
done
