'\" t
.\"     Title: zapish.inc
.\"    Author: Tomasz Kłoczko
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 12/15/2017
.\"    Manual: Library functions
.\"    Source: zapish.inc
.\"  Language: English
.\"
.TH "ZAPISH\&.INC" "3" "12/15/2017" "zapish\&.inc" "Library functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zapish.inc \- Zabbix API SH interface
.SH "SYNOPSIS"
.HP \w'\fB\&.\ /usr/libexec/zapish\&.inc\fR\ 'u
\fB\&. /usr/libexec/zapish\&.inc\fR
.SH "DESCRIPTION"
.PP
The
\fBzapish\&.inc\fR
file provides include file which allows easily calling Zabbix API functions from POSIX SH scripts\&.
.SH "FUNCTIONS"
.PP
\fBjson_array_num()\fR
.RS 4
TBD\&.
.RE
.PP
\fBjson_array_str()\fR
.RS 4
TBD\&.
.RE
.PP
\fBjson_list()\fR
.RS 4
TBD\&.
.RE
.PP
\fBjson_num()\fR
.RS 4
TBD\&.
.RE
.PP
\fBjson_str()\fR
.RS 4
TBD\&.
.RE
.PP
\fBzabbix_api()\fR
.RS 4
Main zapish function used to call any zabbix API\&. This function expects a parameter
.RE
.SH "CONFIGURATION"
.PP
The
\fBzapish\&.inc\fR
functions use following configuration variables in
~/\&.zapish\&.rc:
.SH "FILES"
.PP
/usr/libexec/zapish\&.inc
.RS 4
Default location of the zapish\&.inc include file\&.
.RE
.SH "EXIT CODES"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \&The zapish\&.inc functions may exit with the following exit codes:
.TS
allbox tab(:);
cB lB.
T{
Exit code
T}:T{
Description
T}
.T&
c l
c l
c l
c l
c l.
T{
0
T}:T{
success
T}
T{
1
T}:T{
Zabbix API authentication error
T}
T{
2
T}:T{
zapish initialization successful (created ~/\&.zapish\&.rc)
T}
T{
3
T}:T{
zabbix_api() called without arguments
T}
T{
4
T}:T{
zabbix_api() call error
T}
.TE
.sp 1
.SH "SEE ALSO"
.PP
\fBsh\fR(1)
.PP
\m[blue]\fB\%https://github.com/kloczek/zapish/\fR\m[]
.PP
\m[blue]\fB\%https://www.zabbix.com/documentation/3.4/manual/api/\fR\m[]
.SH "AUTHOR"
.PP
\fBTomasz Kłoczko\fR
.RS 4
Creation, 2017
.RE
.SH "COPYRIGHT"
.br
