#!/bin/sh

. ../zapish.sh

template_name="ICMP"

templates=$(zabbix_api template.get \
	"$(json_list params \
		"$(json_str output simple \
		"")" \
		"$(json_list filter \
			"$(json_array_str host \
				"${template_name}" \
			"")" \
		"")" \
	"")" \
)

templateid="$(json_get "${templates=}" .result[].templateid)"

xml_output=$(zabbix_api configuration.export \
	"$(json_list params \
		"$(json_list options \
			"$(json_array_num templates \
				${templateid} \
			"")" \
		"")" \
		"$(json_str format xml \
		"")" \
	"")" \
)

echo "Template: id=${templateid}, Name=\"${template_name}\" dump to ${template_name}.xml and ${template_name}.raw"
echo ${xml_output} | jq -r .result | xmllint --format - > ${template_name}.xml
echo ${xml_output} | jq .result > ${template_name}.raw
