#!/bin/sh

. ../zapish.inc

# Get all templates IDs
json_get "$(zabbix_api template.get \
		"$(json_list params \
			"$(json_str output extend \
			"")" \
		"")" \
	)" '.result[].name' | \
while read template_name; do
	# strip down leading and trailing " \
	template_name="${template_name:1:-1}" \
	template_id="$(json_get "$(zabbix_api template.get \
		"$(json_list params \
			"$(json_list "filter" \
				"$(json_str "name" \
					"${template_name}" \
				"")" \
			"")" \
			"$(json_str "output" "simple" \
			"")" \
		"")" \
	)" .result[].templateid)"

	xml_output="$(zabbix_api configuration.export \
		"$(json_list params \
			"$(json_list options \
				"$(json_array_num templates \
					${template_id} \
				"")" \
			"")" \
			"$(json_str format xml \
			"")" \
		"")" \
	)"

	printf "Template id=%7s, Name=%-40s dump to \"%s.xml\"\n" ${template_id} "\"${template_name}\"" "${template_name}"
	echo "${xml_output}" | jq -r .result | xmllint --format - > ${template_name}.xml
	#echo "Template: id=${templateid}, Name=\"${template_name}\" dump to ${template_name}.raw"
	#echo "${xml_output}" | jq .result > ${template_name}.raw
done

