#!/bin/sh

if [ -e ../zapish.inc ]; then
	. ../zapish.inc
elif [ -e /usr/libexec/zapish/zapish.inc ]; then
	. /usr/libexec/zapish/zapish.inc
else
	echo "No zapish.inc found"
	exit 1
fi

template_name="ICMP"

templates=$(zabbix_api template.get \
	"$(json_list params \
		"$(json_str output simple \
		"")" \
		"$(json_list filter \
			"$(json_array_str "name" \
				"${template_name}" \
			"")" \
		"")" \
	"")" \
)

templateid="$(json_get "${templates=}" '.result[].templateid')"

xml_output=$(zabbix_api configuration.export \
	"$(json_list params \
		"$(json_list options \
			"$(json_array_num templates \
				${templateid} \
			"")" \
		"")" \
		"$(json_str format xml \
		"")" \
	"")" \
)

echo "Template: id=${templateid}, Name=\"${template_name}\" dump to ${template_name}.xml and ${template_name}.raw"
echo ${xml_output} | jq -r .result | xmllint --format - > ${template_name}.xml
echo ${xml_output} | jq .result > ${template_name}.raw
